### ISSUE TITLE
Make Chromium xterm as nice as Fx

### ISSUE THREAD

**Issue by beaufortfrancois** [jankeromnes/dockerfiles#10]
I don't have `history` commands, `<up>` and `<down>` keys don't work, and even completion doesn't work.

**Comment by jankeromnes** [comment]
Thanks for reporting this issue! As you correctly identified on IRC, the problem was that only Firefox,Thunderbird and Servo images used `bash` as default shell. Chrome and KDE images didn't specify a `SHELL` environment variable, so the default `sh` was used (which doesn't have all the nice things you requested).

Fixed by a6573f11018e632293777377bf65dcc0bb875d30, which means the next round of image updates should contain the fix. Hopefully this will make your `xterm` experience on Janitor a lot nicer!
